# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databoard', '0003_auto_20170922_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='freq',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mydata',
            name='method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
